

class PromptManager:

    @staticmethod
    def hot_take_data_extraction_prompt():
        return f"""
            Given the provided instruction, extract the news URL, intention, and key people from the instruction.
            If the instruction is not clear, or the information is not present, return `None` in the respective fields.
        """

    @staticmethod
    def news_data_extraction_prompt():
        return f"""
            Given the provided news URL, extract the title, description, detailed summary, and key points from the news article.
            If the news URL is not clear, or the information is not present, return `None` in the respective fields.
        """

    @staticmethod
    def status_prompt_template(persona_template, avatar_name, date_and_time) -> str:
        """
        This constructs a quick status update to be generated by the LLM.
        """
        return f"""
            {persona_template}\n\n
            {date_and_time}
            Using the provided information, craft an interesting and engaging twitter status update that {avatar_name}
            can post. Ensure it is engaging, slightly controversial, and maximises engagement.\n\n
        """

    @staticmethod
    def _status_retry_prompt_template(persona_template, avatar_name, caption) -> str:
        """
        This constructs the prompt to modify generated statuses that are longer than Twitters permitted 280 chars.
        """

        return f"""
                {persona_template}\n\n
                {avatar_name} has generated the following caption to post to their Twitter timeline. Unfortunately, this
                caption is over the permitted 280 character limit on Twitter: \n\n
                {caption} \n\n
                Using your judgement, regenerate the caption to something more succinct. If the caption 
                does not make sense with less characters, or loses its essence, generate an entirely new caption that is
                similar, and also witty, exciting, and slightly controversial.

            """