# Generated by Django 4.2.8 on 2023-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='action',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
