# Generated by Django 4.2.8 on 2023-12-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='action',
            field=models.TextField(default=None, max_length=2500),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_description',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
