# Generated by Django 4.2.8 on 2023-12-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_image_description_remove_post_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=None, max_length=2500, null=True),
        ),
    ]
