# Generated by Django 4.2.8 on 2023-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='action',
            field=models.TextField(default=None, max_length=2500, null=True),
        ),
    ]
