# Generated by Django 4.2.8 on 2023-12-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='twitter_media_id',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
