# Generated by Django 4.2.8 on 2023-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_media_twitter_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='twitter_preview_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='twitter_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
