# Generated by Django 4.2.8 on 2023-12-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='user.user')),
            ],
            options={
                'db_table': 'avatar',
            },
        ),
        migrations.CreateModel(
            name='CaptionTemplate',
            fields=[
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='caption_templates', serialize=False, to='avatar.avatar')),
                ('caption_theme', models.CharField(max_length=1000)),
                ('example_captions', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'avatar_caption_template',
            },
        ),
        migrations.CreateModel(
            name='ImageTemplate',
            fields=[
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image_templates', serialize=False, to='avatar.avatar')),
                ('visual_style', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'avatar_image_template',
            },
        ),
        migrations.CreateModel(
            name='PersonaTemplate',
            fields=[
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona_template', serialize=False, to='avatar.avatar')),
                ('personality', models.CharField(max_length=1000)),
                ('audience', models.CharField(max_length=1000)),
                ('vision', models.CharField(max_length=1000)),
                ('purpose', models.CharField(max_length=1000)),
                ('values', models.CharField(max_length=1000)),
                ('additional_info', models.CharField(max_length=1000)),
                ('career', models.CharField(max_length=1000)),
                ('hobbies', models.CharField(max_length=1000)),
                ('tone', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'avatar_persona_template',
            },
        ),
    ]
