# Generated by Django 4.2.8 on 2023-12-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_alter_personatemplate_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captiontemplate',
            name='avatar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='caption_template', serialize=False, to='avatar.avatar'),
        ),
        migrations.AlterField(
            model_name='imagetemplate',
            name='avatar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image_template', serialize=False, to='avatar.avatar'),
        ),
    ]
