# Generated by Django 4.2.8 on 2023-12-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_alter_captiontemplate_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captiontemplate',
            name='caption_theme',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='captiontemplate',
            name='example_captions',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='imagetemplate',
            name='visual_style',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='additional_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='audience',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='career',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='hobbies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='personality',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='purpose',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='tone',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='values',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personatemplate',
            name='vision',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
