# Generated by Django 4.2.8 on 2023-12-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0004_alter_captiontemplate_caption_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captiontemplate',
            name='caption_length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
